### ISSUE TITLE
React UI

### ISSUE THREAD

**Issue by rahulkumar96t** [aws-samples/amazon-ivs-multi-host-serverless-demo#4]
Is there any React UI to test this demo.

**Comment by slee-aws** [comment]
Hello @rahulkumar96t, no there is currently not a react UI for this demo. However, there is a React sample available in the web broadcast SDK guide, which you may find helpful: https://aws.github.io/amazon-ivs-web-broadcast/docs/real-time-sdk-guides/introduction
